config/routes.rb
Uop::Application.routes.draw do
  resources :mainpages

   root 'mainpages#index'

end

app/models/mainpage.rb
class Mainpage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mainpages_controller.rb
class MainpagesController < ApplicationController
  before_action :set_mainpage, only: [:show, :edit, :update, :destroy]

  # GET /mainpages
  # GET /mainpages.json
  def index
    @mainpages = Mainpage.all
  end

  # GET /mainpages/1
  # GET /mainpages/1.json
  def show
  end

  # GET /mainpages/new
  def new
    @mainpage = Mainpage.new
  end

  # GET /mainpages/1/edit
  def edit
  end

  # POST /mainpages
  # POST /mainpages.json
  def create
    @mainpage = Mainpage.new(mainpage_params)

    respond_to do |format|
      if @mainpage.save
        format.html { redirect_to @mainpage, notice: 'Mainpage was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mainpage }
      else
        format.html { render action: 'new' }
        format.json { render json: @mainpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mainpages/1
  # PATCH/PUT /mainpages/1.json
  def update
    respond_to do |format|
      if @mainpage.update(mainpage_params)
        format.html { redirect_to @mainpage, notice: 'Mainpage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mainpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mainpages/1
  # DELETE /mainpages/1.json
  def destroy
    @mainpage.destroy
    respond_to do |format|
      format.html { redirect_to mainpages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mainpage
      @mainpage = Mainpage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mainpage_params
      params.require(:mainpage).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mainpages_helper.rb
module MainpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mainpages/_form.html.erb
<%= form_for(@mainpage) do |f| %>
  <% if @mainpage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mainpage.errors.count, "error") %> prohibited this mainpage from being saved:</h2>

      <ul>
      <% @mainpage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mainpages/edit.html.erb
<h1>Editing mainpage</h1>

<%= render 'form' %>

<%= link_to 'Show', @mainpage %> |
<%= link_to 'Back', mainpages_path %>

app/views/mainpages/index.html.erb
<h1>Listing mainpages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mainpages.each do |mainpage| %>
      <tr>
        <td><%= mainpage.name %></td>
        <td><%= mainpage.content %></td>
        <td><%= link_to 'Show', mainpage %></td>
        <td><%= link_to 'Edit', edit_mainpage_path(mainpage) %></td>
        <td><%= link_to 'Destroy', mainpage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mainpage', new_mainpage_path %>

app/views/mainpages/new.html.erb
<h1>New mainpage</h1>

<%= render 'form' %>

<%= link_to 'Back', mainpages_path %>

app/views/mainpages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mainpage.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @mainpage.content %>
</p>

<%= link_to 'Edit', edit_mainpage_path(@mainpage) %> |
<%= link_to 'Back', mainpages_path %>